### ISSUE TITLE
How to project spherical angles on to a plane infront of the user.

### ISSUE THREAD

**Issue by UlascanErsoy** [UlascanErsoy/Team-7---Multimodal-Accessibility#14]

**Comment by YSChen0609** [comment]
https://github.com/lockepatton/sonipy/tree/master

**Comment by UlascanErsoy** [comment]
I think we can count this as resolved for now.

This was addressed in both da7fee92bc6b8878d4adae254df6be4d7a1f82b0 and f2e0b56e105c4b842728ad2a7c455e1e4baa6acd.
