### ISSUE TITLE
Literature Review For Spatial Audio

### ISSUE THREAD

**Issue by UlascanErsoy** [UlascanErsoy/Team-7---Multimodal-Accessibility#7]

**Comment by YSChen0609** [comment]
-  https://www.interaction-design.org/literature/topics/spatial-audio?srsltid=AfmBOorwe66EEmPPIj8kOmK2Eq3JRR6-l8gozG8axRc7eEOTHJFJeFh0
- https://www.semanticscholar.org/reader/2b3ddaf39d70bd4d1337708c756692f687d18d10

**Comment by UlascanErsoy** [comment]
Original paper for the HRTF (Head related transfer function) paper, and a python implementation of the transfer function using the database. 

- [CIPIC HRTF](https://www.ece.ucdavis.edu/cipic/wp-content/uploads/sites/12/2015/04/cipic_WASSAP_2001_143.pdf)
- [Github](https://github.com/franciscorotea/3D-Audio-Panner.git)

**Comment by YSChen0609** [comment]
Perplexity Search
- https://www.perplexity.ai/search/papers-about-data-visualizatio-fXmXdrlxR6Wms.8gXQghdw
- https://www.perplexity.ai/search/papers-about-using-hrtf-spatia-9FgTRWa9Q..k6CcJAQ43_g

Highly Recommended
- https://asmp-eurasipjournals.springeropen.com/articles/10.1186/s13636-022-00242-x

Just a cool paper
- https://arxiv.org/html/2405.07089v1

**Comment by YSChen0609** [comment]
Highly Recommend:
- https://asmp-eurasipjournals.springeropen.com/articles/10.1186/s13636-022-00242-x
